# Generated by Django 3.2 on 2021-07-18 10:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2021, 7, 18, 10, 52, 31, 995018, tzinfo=utc))),
                ('updated_at', models.DateField(verbose_name=datetime.datetime(2021, 7, 18, 10, 52, 31, 996016, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
