# Generated by Django 3.2 on 2021-07-18 14:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('catergory', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2021, 7, 18, 14, 14, 14, 176698, tzinfo=utc))),
                ('updated_at', models.DateField(verbose_name=datetime.datetime(2021, 7, 18, 14, 14, 14, 176698, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
